//
// Created by haridev on 10/5/23.
//

#ifndef HPC_DEBUGGER_CONSTANTS_H
#define HPC_DEBUGGER_CONSTANTS_H

#define HPC_DEBUGGER_CONFIGURATION "HPC_DEBUGGER_CONFIGURATION"
#define HPC_DEBUGGER_DEBUG_FILE "HPC_DEBUGGER_DEBUG_FILE"
#define HPC_DEBUGGER_DEBUG_PORT "HPC_DEBUGGER_DEBUG_PORT"

#endif // HPC_DEBUGGER_CONSTANTS_H